openapi: 3.0.0
info:
  title: Natours API Documentation
  version: 1.0.0
paths:
  /tours:
    get:
      summary: GET all Tours
      description: This path will retrieve all the available tours and send them as a JSON object containing all of their data.
      parameters:
        - $ref: '#/components/parameters/durationParam'
        - $ref: '#/components/parameters/durationLtParam'
        - $ref: '#/components/parameters/durationGtParam'
        - $ref: '#/components/parameters/durationLteParam'
        - $ref: '#/components/parameters/durationGteParam'
        - $ref: '#/components/parameters/priceParam'
        - $ref: '#/components/parameters/priceLtParam'
        - $ref: '#/components/parameters/priceGtParam'
        - $ref: '#/components/parameters/priceLteParam'
        - $ref: '#/components/parameters/priceGteParam'
        - $ref: '#/components/parameters/ratingsAverageParam'
        - $ref: '#/components/parameters/ratingsQuantityParam'
      responses:
        '200':
          description: Successfull retrieved all Tours.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: number
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            startLocation:
                              type: object
                              properties:
                                type:
                                  type: string
                                coordinates:
                                  type: array
                                  items:
                                    type: number
                                address:
                                  type: string
                                description:
                                  type: string
                            _id:
                              type: string
                            name:
                              type: string
                            duration:
                              type: number
                            maxGroupSize:
                              type: number
                            difficulty:
                              type: string
                            ratingsAverage:
                              type: number
                            ratingsQuantity:
                              type: number
                            price:
                              type: number
                            locations:
                              type: array
                              items:
                                type: object
                                properties:
                                  type:
                                    type: string
                                  coordinates:
                                    type: array
                                    items:
                                      type: number
                                  description:
                                    type: string
                                  day:
                                    type: number
                                  _id:
                                    type: string
                                  id:
                                    type: string
                            guides:
                              type: array
                              items:
                                type: object
                                properties:
                                  _id:
                                    type: string
                                  name:
                                    type: string
                                  email:
                                    type: string
                                  role:
                                    type: string
                                  photo:
                                    type: string
                            slug:
                              type: string
                            durationWeeks:
                              type: number
                            id:
                              type: string
components:
  parameters:
    durationParam:
      name: duration
      in: query
      description: Filter for the durations equal to VALUE
      schema:
        type: string
      style: form
    durationLtParam:
      name: duration[lt]
      in: query
      description: Filter for the durations less than VALUE
      schema:
        type: number
      style: form
    durationGtParam:
      name: duration[gt]
      in: query
      description: Filter for the durations greater than VALUE
      schema:
        type: number
      style: form
    durationLteParam:
      name: duration[lte]
      in: query
      description: Filter for the durations less than or equal to VALUE
      schema:
        type: number
      style: form
    durationGteParam:
      name: duration[lte]
      in: query
      description: Filter for the durations greater than or equal to VALUE
      schema:
        type: number
      style: form
    priceParam:
      name: price
      in: query
      description: Filter for price equal to VALUE
      schema:
        type: number
      style: form
    priceLtParam:
      name: price[lt]
      in: query
      description: Filter for price less than VALUE
      schema:
        type: number
      style: form
    priceGtParam:
      name: price[gt]
      in: query
      description: Filter for price greater than VALUE
      schema:
        type: number
      style: form
    priceLteParam:
      name: price[lte]
      in: query
      description: Filter for price less than or equal to VALUE
      schema:
        type: number
      style: form
    priceGteParam:
      name: price[gte]
      in: query
      description: Filter for price greater than or equal to VALUE
      schema:
        type: number
      style: form
    ratingsAverageParam:
      name: ratingsAverage
      in: query
      description: Filter by the average ratings.
      schema:
        type: number
      style: form
      examples:
        none:
          value: ''
        equalTo:
          value: 'ratingsAverage='
        greaterThan:
          value: 'ratingsAverage[gt]='
        lessThan:
          value: 'ratingsAverage[lt]='
        greaterThanEqualTo:
          value: 'ratingsAverage[gte]='
        lessThanEqualTo:
          value: 'ratingsAverage[lte]='
    ratingsQuantityParam:
      name: ratingsQuantity
      in: query
      description: Filter by the number of ratings.
      schema:
        type: number
      style: form
      examples:
        none:
          value: ''
        equalTo:
          value: 'ratingsQuantity='
        greaterThan:
          value: 'ratingsQuantity[gt]='
        lessThan:
          value: 'ratingsQuantity[lt]='
        greaterThanEqualTo:
          value: 'ratingsQuantity[gte]='
        lessThanEqualTo:
          value: 'ratingsQuantity[lte]='
servers:
  - url: http://127.0.0.1:3000/api/v1
